---
version: "3.2"

services:

  database:
    image: mysql
    secrets:
      - db_root_password
      - db_user_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/db_root_password'
      MYSQL_DATABASE: 'giftme'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD_FILE: '/run/secrets/db_user_password'
    volumes:
      - database:/var/lib/mysql
    networks:
      - back

  php:
    user: '1000'
    image: louisbilliet/giftme_php:${TAG:-dev}
    secrets:
      - db_user_password
    environment:
      DB_HOST: database
      DB_DATABASE: giftme
      DB_USERNAME: laravel
      MAIL_DRIVER: smtp
      MAIL_HOST: mailcatcher
      MAIL_PORT: 1025
      APP_KEY: "base64:Ji1Tvm/1/Z6SKny3aeajarGtcf2r7LjYFRM39f6JLtw="
    networks:
      - front
      - back
    deploy:
      restart_policy:
        condition: any
        delay: 1s

volumes:
  database: {}

networks:
  front:
  back:

secrets:
  db_root_password:
    file: .root_passwd
  db_user_password:
    file: .user_passwd
