---
version: "3.1"

services:

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'TooSecure'
      MYSQL_DATABASE: 'giftme'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: 'secure'
    volumes:
      - database:/var/lib/mysql

  nginx:
    image: nginx
    ports:
    - "8080:80"
    volumes:
      - ../code:/app
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
    - php

  php:
    user: '1000'
    build: ./php
    environment:
      DB_HOST: database
      DB_DATABASE: giftme
      DB_USERNAME: laravel
      DB_PASSWORD: secure
    volumes:
      - ../code:/app
    links:
      - database

volumes:
  database: {}
