---
version: "3.2"

services:

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - target: 1080
        published: 1080
        protocol: TCP
        mode: host
    networks:
      - front
      - back

  database:
    image: mysql
    secrets:
      - db_root_password
      - db_user_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/db_root_password'
      MYSQL_DATABASE: 'giftme'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD_FILE: '/run/secrets/db_user_password'
    volumes:
      - database:/var/lib/mysql
    networks:
      - back

  nginx:
    image: giftme_nginx:dev
    ports:
      - target: 80
        published: 8080
        protocol: TCP
        mode: host
    volumes:
      - ../code:/app
    networks:
      - front
      - back

  php:
    user: '1000'
    image: giftme_php:dev
    secrets:
      - db_user_password
    environment:
      DB_HOST: database
      DB_DATABASE: giftme
      DB_USERNAME: laravel
      MAIL_DRIVER: smtp
      MAIL_HOST: mailcatcher
      MAIL_PORT: 1025
    volumes:
      - ../code:/app
    networks:
      - front
      - back

  node:
    user: '1000'
    image: giftme_node:dev
    volumes:
      - ../code:/app

volumes:
  database: {}

networks:
  front:
  back:

secrets:
  db_root_password:
    file: .root_passwd
  db_user_password:
    file: .user_passwd
