---
version: "3.1"

services:

  nginx:
    image: nginx
    ports:
    - "8080:80"
    volumes:
    - ../code:/app
    - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
    - php

  php:
    image: php:7-fpm
    volumes:
    - ../code:/app
